import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import Content from "~/components/Content";
import { Header } from "~/components/Header";
import { api } from "~/utils/api";

const HabitPage: NextPage = () => {
  const { query } = useRouter();
  const { id } = query as { id: string };
  const habit = api.habit.getHabitById.useQuery({ id });
  return (
    <>
      <Head>
        <title>Tracker App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-gray-900 text-white">
        <Header />
        {habit.data?.name}
      </main>
    </>
  );
};

export default HabitPage;
