import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'About | Next App',
  description: 'Generated by create next app',
};

export default function About() {
  return <h3>This is about page</h3>;
}
