import { type NextPage } from "next";
import Head from "next/head";
import { Content } from "~/components/content";

import { Layout } from "~/components/shared/Layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Tracker App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Content />
      </Layout>
    </>
  );
};

export default Home;
